CLOCKIFY_API_KEY = 'your_api_key'
CLOCKIFY_BASE_URL = 'https://api.clockify.me/api/v1'
CLOCKIFY_WORKSPACE_ID = 'your_workspace_id'
GOOGLE_SHEETS_CREDENTIALS_FILE = 'path/to/credentials.json'
GOOGLE_OAUTH_TOKEN_FILE = 'path/to/token.json'
SPREADSHEET_ID = 'your_spreadsheet_id'